### ISSUE TITLE
Twopence should supply a API to detect whether TARGET machine can be connected

### ISSUE THREAD

**Issue by XGWang0** [openSUSE/twopence#41]
I do not know if current twopence has supplied the API which can detect the TARGET machine can be connected or not after it is rebooted. In actual, we usually meet TARGET reboot situation, once TARGET is rebooted, we will not do anything via twopence,  only depend on other tool to check whether TARGET is connetable.

**Comment by Bischoff** [comment]
Hmmm.

Not a bad idea, but to do this, twopence would have to either ping the machine all the time, or try to send twopence commands with a short timeout.

First solution (ping) is bad as a generic solution because it would not work if the machine has no network connection and you are using virtio or serial.

For both solutions, you can achieve exactly the same by doing a loop in your script, so there is not much point in doing it in twopence.

I would rather advice you do a reasonable "sleep" in your script to let the machine enough time to boot.

I'll leave the issue open and if no one comes up with better solutions, I will close it.

**Comment by MalloZup** [comment]
Hi, think the same a @Bischoff  here, you could add the wait_reboot call on your library/script

**Comment by Bischoff** [comment]
This might be a job for SUSEtest though. Feel free to open equivalent issue against SUSEtest library.

**Comment by MalloZup** [comment]
yop,  i have already putted it in a TODO list in the system.py library:

https://github.com/okirch/susetest/blob/master/susetest/python/susetest_api/system.py#L32

**Comment by XGWang0** [comment]
Thanks all.
